export const eventCardsData = [
  {
    date: '01.May.2023',
    content: 'New Event Created',
    event: 'East African Party',
    location: 'BK Arena',
    status: 'Live',
    live: 'Updated today',
  },
  {
    date: '01.May.2023',
    content: 'New Event Created',
    event: 'East African Party',
    location: 'BK Arena',
    status: 'Live',
    live: 'Updated today',
  },
  {
    date: '01.May.2023',
    content: 'New Event Created',
    event: 'East African Party',
    location: 'BK Arena',
    status: 'Live',
    live: 'Updated today',
  },
  {
    date: '01.May.2023',
    content: 'New Event Created',
    event: 'East African Party',
    location: 'BK Arena',
    status: 'Live',
    live: 'Updated today',
  },
  {
    date: '01.May.2023',
    content: 'New Event Created',
    event: 'East African Party',
    location: 'BK Arena',
    status: 'Live',
    live: 'Updated today',
  },
  {
    date: '01.May.2023',
    content: 'New Event Created',
    event: 'East African Party',
    location: 'BK Arena',
    status: 'Live',
    live: 'Updated today',
  },
]
